include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/building/maven/library.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/scanning/dependency-scanning.yml'
  - template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - test

sast:
  stage: test
